'use strict';

const BATCH_STATES = Object.freeze({
  QUEUED: 'queued',
  CREATING_ALIASES: 'creating_aliases',
  ALLOCATING_PROXIES: 'allocating_proxies',
  SUBMITTING: 'submitting',
  SUBMIT_UNKNOWN: 'submit_unknown',
  ACCEPTED: 'accepted',
  RUNNING: 'running',
  COLLECTING_RESULTS: 'collecting_results',
  COMPLETED: 'completed',
  PARTIAL_COMPLETED: 'partial_completed',
  FAILED: 'failed',
});

const BATCH_EVENTS = Object.freeze({
  START: 'start',
  ALIASES_CREATED: 'aliases_created',
  PROXIES_ALLOCATED: 'proxies_allocated',
  SUBMIT_ACCEPTED: 'submit_accepted',
  SUBMIT_UNCERTAIN: 'submit_uncertain',
  EXTERNAL_STARTED: 'external_started',
  EXTERNAL_FINISHED: 'external_finished',
  COMPLETE: 'complete',
  COMPLETE_PARTIAL: 'complete_partial',
  FAIL: 'fail',
  RECONCILE_ACCEPTED: 'reconcile_accepted',
});

const TASK_STATES = Object.freeze({
  ALIAS_READY: 'alias_ready',
  SUBMITTED: 'submitted',
  RUNNING: 'running',
  REGISTERED: 'registered',
  QUALIFIED: 'qualified',
  UNQUALIFIED: 'unqualified',
  MFA_FAILED: 'mfa_failed',
  FAILED: 'failed',
  SAVED: 'saved',
  RELEASED: 'released',
});

const TASK_EVENTS = Object.freeze({
  SUBMIT: 'submit',
  START: 'start',
  REGISTER: 'register',
  QUALIFY: 'qualify',
  REJECT_QUALIFICATION: 'reject_qualification',
  MFA_FAIL: 'mfa_fail',
  FAIL: 'fail',
  SAVE: 'save',
  RELEASE: 'release',
});

function map(entries) {
  return new Map(entries.map(([state, events]) => [state, new Map(Object.entries(events))]));
}

const BATCH_TRANSITIONS = map([
  [BATCH_STATES.QUEUED, { [BATCH_EVENTS.START]: BATCH_STATES.CREATING_ALIASES, [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED }],
  [BATCH_STATES.CREATING_ALIASES, { [BATCH_EVENTS.ALIASES_CREATED]: BATCH_STATES.ALLOCATING_PROXIES, [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED }],
  [BATCH_STATES.ALLOCATING_PROXIES, { [BATCH_EVENTS.PROXIES_ALLOCATED]: BATCH_STATES.SUBMITTING, [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED }],
  [BATCH_STATES.SUBMITTING, {
    [BATCH_EVENTS.SUBMIT_ACCEPTED]: BATCH_STATES.ACCEPTED,
    [BATCH_EVENTS.SUBMIT_UNCERTAIN]: BATCH_STATES.SUBMIT_UNKNOWN,
    [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED,
  }],
  [BATCH_STATES.SUBMIT_UNKNOWN, {
    [BATCH_EVENTS.RECONCILE_ACCEPTED]: BATCH_STATES.ACCEPTED,
    [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED,
  }],
  [BATCH_STATES.ACCEPTED, {
    [BATCH_EVENTS.EXTERNAL_STARTED]: BATCH_STATES.RUNNING,
    [BATCH_EVENTS.EXTERNAL_FINISHED]: BATCH_STATES.COLLECTING_RESULTS,
    [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED,
  }],
  [BATCH_STATES.RUNNING, { [BATCH_EVENTS.EXTERNAL_FINISHED]: BATCH_STATES.COLLECTING_RESULTS, [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED }],
  [BATCH_STATES.COLLECTING_RESULTS, {
    [BATCH_EVENTS.COMPLETE]: BATCH_STATES.COMPLETED,
    [BATCH_EVENTS.COMPLETE_PARTIAL]: BATCH_STATES.PARTIAL_COMPLETED,
    [BATCH_EVENTS.FAIL]: BATCH_STATES.FAILED,
  }],
  [BATCH_STATES.COMPLETED, {}],
  [BATCH_STATES.PARTIAL_COMPLETED, {}],
  [BATCH_STATES.FAILED, {}],
]);

const TASK_TRANSITIONS = map([
  [TASK_STATES.ALIAS_READY, { [TASK_EVENTS.SUBMIT]: TASK_STATES.SUBMITTED, [TASK_EVENTS.FAIL]: TASK_STATES.FAILED, [TASK_EVENTS.RELEASE]: TASK_STATES.RELEASED }],
  [TASK_STATES.SUBMITTED, { [TASK_EVENTS.START]: TASK_STATES.RUNNING, [TASK_EVENTS.REGISTER]: TASK_STATES.REGISTERED, [TASK_EVENTS.FAIL]: TASK_STATES.FAILED }],
  [TASK_STATES.RUNNING, { [TASK_EVENTS.REGISTER]: TASK_STATES.REGISTERED, [TASK_EVENTS.FAIL]: TASK_STATES.FAILED }],
  [TASK_STATES.REGISTERED, {
    [TASK_EVENTS.QUALIFY]: TASK_STATES.QUALIFIED,
    [TASK_EVENTS.REJECT_QUALIFICATION]: TASK_STATES.UNQUALIFIED,
    [TASK_EVENTS.MFA_FAIL]: TASK_STATES.MFA_FAILED,
    [TASK_EVENTS.FAIL]: TASK_STATES.FAILED,
  }],
  [TASK_STATES.QUALIFIED, { [TASK_EVENTS.SAVE]: TASK_STATES.SAVED, [TASK_EVENTS.MFA_FAIL]: TASK_STATES.MFA_FAILED, [TASK_EVENTS.FAIL]: TASK_STATES.FAILED }],
  [TASK_STATES.UNQUALIFIED, { [TASK_EVENTS.RELEASE]: TASK_STATES.RELEASED }],
  [TASK_STATES.MFA_FAILED, { [TASK_EVENTS.RELEASE]: TASK_STATES.RELEASED }],
  [TASK_STATES.FAILED, { [TASK_EVENTS.RELEASE]: TASK_STATES.RELEASED }],
  [TASK_STATES.SAVED, { [TASK_EVENTS.RELEASE]: TASK_STATES.RELEASED }],
  [TASK_STATES.RELEASED, {}],
]);

function next(entity, transitions, state, event) {
  const value = transitions.get(state)?.get(event);
  if (!value) {
    const error = new Error(`invalid ${entity} transition: ${state} + ${event}`);
    error.code = 'INVALID_REGISTRATION_TRANSITION';
    throw error;
  }
  return value;
}

function nextBatchState(state, event) {
  return next('batch', BATCH_TRANSITIONS, state, event);
}

function nextTaskState(state, event) {
  return next('task', TASK_TRANSITIONS, state, event);
}

module.exports = {
  BATCH_EVENTS,
  BATCH_STATES,
  TASK_EVENTS,
  TASK_STATES,
  nextBatchState,
  nextTaskState,
};
